# Port
server:
  port: 8080

  #logging:
      #config: classpath:log4j2-boot-dev.xml

spring:
  application:
    # apply name
    name: michael-ou-transaction
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/doms?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #Configure multiple English comma separated (statistics, SQL injection, log4j filtering)
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
#mybatis:
  # mybatis Path of configuration file
  #config-location: classpath:mybatis.cfg.xml
  #type-aliases-package: com.michael.pay.service
  # mapper Mapping file
  #mapper-locations: classpath:mapper/*.xml




